site_name: Cookie Docs
site_url: https://docs.cookieapp.me
theme:
  name: material
  language: en
  logo: https://cdn.cookieapp.me/bot/logo.png
  favicon: https://cdn.cookieapp.me/bot/logo.png
  font:
    text: Roboto
  features:
    # - navigation.tabs
    - navigation.indexes
    - navigation.footer
  palette:
    # Dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
markdown_extensions:
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Images
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
extra:
  homepage: https://cookieapp.me
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CookieAppTeam/docs
      name: GitHub Repository
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zfvbjTEzv6
      name: Discord Server
    - icon: fontawesome/solid/cookie
      link: https://cookieapp.me/
      name: Cookie's Website
    - icon: material/shield-check
      link: https://legal.cookieapp.me
      name: Legal Notice & Privacy Policy
plugins:
  - glightbox
  - search
  - git-revision-date-localized
  - git-committers:
      repository: CookieAppTeam/docs
      branch: main
nav:
  - ğŸ  Home: index.md
  - âœ¨ Customization: customization.md
  - ğŸ² Games: games.md
  - ğŸª Economy: economy.md
  - ğŸ§° Server Features:
    - features/index.md
    - Birthday: features/birthday.md
    - Giveaway: features/giveaway.md
    - Leveling: features/leveling.md
    - Server Banner: features/banner.md
    - Stats: features/stats.md
    - TempVoice: features/tempvoice.md
    - Tickets: features/tickets.md
    - Welcome Messages: features/welcome.md
  - ğŸ‘¥ User Features: user_features.md
  - ğŸ’ Cookie Premium: premium.md
  - â“ FAQ: faq.md
